spring:
  application:
    name: kafka-streams-service
  profiles:
    active: kafka_streams
  config:
    import: 'configserver:'
  cloud:
    config:
      name: kafka-streams-service,config-client
      username: spring_cloud_user
      password: '{cipher}2ca52e09ec85aa620abce2e704242985bf786c9a684461b023a563b34b96c527ec81160eae48d731017c98ee0b9e1824'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2

log:
  app-name: kafka-streams-service